#!/usr/bin/env lua

-- # ITEM_DIR="$CONFIG_DIR/items"
-- # source "$ITEM_DIR/bar.sh"
-- # source "$ITEM_DIR/default.sh"
-- # source "$ITEM_DIR/workspaces.sh"
-- # source "$ITEM_DIR/indicator.sh"

-- https://github.com/FelixKratz/SbarLua
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"
sbar = require("sketchybar")

-- Bundle the entire initial configuration into a single message to sketchybar
sbar.begin_config()
require("bar")
require("default")
require("items")
sbar.end_config()

-- Run the event loop of the sketchybar module (without this there will be no
-- callback functions executed in the lua module)
sbar.event_loop()
